export const getCategories = () => ({
    category: [
        'Combo Para Duas Pessoas',
        'Combos',
        'Lanche do mês',
        'Que tal Combo com Sorvete?',
        'Hamburguers',
        'Just Kids',
        'Porções',
        'Saladas'
    ]
})

export const getProducts = () => ({
    products: [
        {
            product_id: `${Math.round(Math.random() * 1000)}`,
            name: 'Combo House para 2 Pessoas',
            price: '89,00',
            category_id: 0,
            ingredients: 'Pão tradicional, Hamburguer 150g, Cheddar, Mayo, Cebola Roxa, Bacon e Molho Just. 1 Batata Palito Grande 2 Refrigerante 350ml Lata',
            description: 'DE 104,00 por 89,00 Combo 2 Just House',
            product_image_url: 'https://files.menudino.com/cardapios/2305/610.jpg',
        },
        {
            product_id: `${Math.round(Math.random() * 1000)}`,
            name: 'Combo Top Smash para 2 Pessoas',
            price: '89,00',
            category_id: 0,
            ingredients: 'Hambúrguer de 150 gr, pão, bacon, queijo, cheddar, cebola caramelizada, picles, mayo, molho especial',
            description: 'De 108,00 por 93,00 1 Lanche Top Smash, 1 Batata individual pequeno, 1 Refrigerante 350ml lata, Ingredientes do Lanche',
            product_image_url: 'https://files.menudino.com/cardapios/2305/609.jpg',
        },
        {
            product_id: `${Math.round(Math.random() * 1000)}`,
            name: 'JUST COMBO 1',
            price: '48,00',
            category_id: 1,
            ingredients: 'Hambúrguer de 150 gr, pão, bacon, queijo, cheddar, cebola caramelizada, picles, mayo, molho especial',
            description: 'Combo 1 Lanche Top Smash, 1 Batata individual pequeno, 1 Refrigerante 350ml lata, Ingredientes do Lanche :',
            product_image_url: 'https://files.menudino.com/cardapios/2305/183.jpg',
        },
        {
            product_id: `${Math.round(Math.random() * 1000)}`,
            name: 'JUST COMBO 2',
            price: '49,00',
            category_id: 1,
            ingredients: 'Hambúrguer de 150 gr, pão, bacon, queijo, cheddar, cebola caramelizada, picles, mayo, molho especial',
            description: 'Combo 1 Lanche Top Smash, 1 Batata individual pequeno, 1 Refrigerante 350ml lata, Ingredientes do Lanche :',
            product_image_url: 'https://files.menudino.com/cardapios/2305/187.jpg',
        },
        {
            product_id: `${Math.round(Math.random() * 1000)}`,
            name: 'JUST COMBO 3',
            price: '47,00',
            category_id: 1,
            ingredients: 'Hambúrguer de 150 gr, pão, bacon, queijo, cheddar, cebola caramelizada, picles, mayo, molho especial',
            description: 'Combo 1 Lanche Top Smash, 1 Batata individual pequeno, 1 Refrigerante 350ml lata, Ingredientes do Lanche :',
            product_image_url: 'https://files.menudino.com/cardapios/2305/277.jpg',
        },
        {
            product_id: `${Math.round(Math.random() * 1000)}`,
            name: 'JUST COMBO CHICKEN',
            price: '47,00',
            category_id: 1,
            ingredients: 'Pão Frango especial Just temperado Molho de mostarda e mel Mayo Cebola roxa AlfaceHambúrguer de 150 gr, pão, bacon, queijo, cheddar, cebola caramelizada, picles, mayo, molho especial',
            description: 'Combo 1 lanche Just chicken, 1 batata palito pequeno, 1 refrigerante 350 ml lata, Ingredientes: ',
            product_image_url: 'https://files.menudino.com/cardapios/2305/477.jpg',
        },
        {
            product_id: `${Math.round(Math.random() * 1000)}`,
            name: 'Family Soda Bundle',
            price: '35,00',
            category_id: 2,
            ingredients: 'Coca Cola, Pepsi, Sprite, Fanta',
            description: 'Get 4 different sodas for the price of 3. Perfect for family gatherings or parties.',
            product_image_url: 'https://files.menudino.com/cardapios/2305/150.jpg',
        },
        {
            product_id: `${Math.round(Math.random() * 1000)}`,
            name: 'Exotic Juice Combo',
            price: '28,00',
            category_id: 2,
            ingredients: 'Mango Juice, Guava Juice, Passionfruit Juice, Pineapple Juice',
            description: 'A selection of tropical juices to bring some sunshine to your day.',
            product_image_url: 'https://files.menudino.com/cardapios/2305/512.jpg',
        },
        {
            product_id: `${Math.round(Math.random() * 1000)}`,
            name: 'Craft Beer Selection',
            price: '55,00',
            category_id: 2,
            ingredients: 'IPA, Stout, Lager, Ale',
            description: 'Try a variety of our best craft beers with this selection pack.',
            product_image_url: 'https://files.menudino.com/cardapios/2305/276.jpg',
        },
        {
            product_id: `${Math.round(Math.random() * 1000)}`,
            name: 'Healthy Hydration Pack',
            price: '30,00',
            category_id: 2,
            ingredients: 'Coconut Water, Green Tea, Lemon Water, Infused Water',
            description: 'Stay hydrated with our healthy pack of drinks, full of antioxidants and vitamins.',
            product_image_url: 'https://files.menudino.com/cardapios/2305/153.jpg',
        },
        {
            product_id: `${Math.round(Math.random() * 1000)}`,
            name: 'Energy Drink Power Pack',
            price: '42,00',
            category_id: 2,
            ingredients: 'Red Bull, Monster, Rockstar, 5 Hour Energy',
            description: 'Boost your energy levels with this power pack of energy drinks.',
            product_image_url: 'https://files.menudino.com/cardapios/2305/155.jpg',
        },
        {
            product_id: `${Math.round(Math.random() * 1000)}`,
            name: 'Healthy Hydration Pack',
            price: '30,00',
            category_id: 3,
            ingredients: 'Coconut Water, Green Tea, Lemon Water, Infused Water',
            description: 'Stay hydrated with our healthy pack of drinks, full of antioxidants and vitamins.',
            product_image_url: 'https://files.menudino.com/cardapios/52813/61.jpg',
        },
        {
            product_id: `${Math.round(Math.random() * 1000)}`,
            name: 'Energy Drink Power Pack',
            price: '42,00',
            category_id: 3,
            ingredients: 'Red Bull, Monster, Rockstar, 5 Hour Energy',
            description: 'Boost your energy levels with this power pack of energy drinks.',
            product_image_url: 'https://files.menudino.com/cardapios/52813/58.jpg',
        },
        {
            product_id: `${Math.round(Math.random() * 1000)}`,
            name: 'Craft Beer Selection',
            price: '55,00',
            category_id: 4,
            ingredients: 'IPA, Stout, Lager, Ale',
            description: 'Try a variety of our best craft beers with this selection pack.',
            product_image_url: 'https://files.menudino.com/cardapios/2305/276.jpg',
        },
        {
            product_id: `${Math.round(Math.random() * 1000)}`,
            name: 'Healthy Hydration Pack',
            price: '30,00',
            category_id: 4,
            ingredients: 'Coconut Water, Green Tea, Lemon Water, Infused Water',
            description: 'Stay hydrated with our healthy pack of drinks, full of antioxidants and vitamins.',
            product_image_url: 'https://files.menudino.com/cardapios/2305/153.jpg',
        },
        {
            product_id: `${Math.round(Math.random() * 1000)}`,
            name: 'Craft Beer Selection',
            price: '55,00',
            category_id: 4,
            ingredients: 'IPA, Stout, Lager, Ale',
            description: 'Try a variety of our best craft beers with this selection pack.',
            product_image_url: 'https://files.menudino.com/cardapios/2305/276.jpg',
        },
        {
            product_id: `${Math.round(Math.random() * 1000)}`,
            name: 'Healthy Hydration Pack',
            price: '30,00',
            category_id: 4,
            ingredients: 'Coconut Water, Green Tea, Lemon Water, Infused Water',
            description: 'Stay hydrated with our healthy pack of drinks, full of antioxidants and vitamins.',
            product_image_url: 'https://files.menudino.com/cardapios/2305/153.jpg',
        },
        {
            product_id: `${Math.round(Math.random() * 1000)}`,
            name: 'Craft Beer Selection',
            price: '55,00',
            category_id: 5,
            ingredients: '1 cheese burger (ou nugetts), fritas 1 refrigerante pequeno ou suco de caixinha',
            description: 'caixinha personalizada infantil com uma lembrancinha',
            product_image_url: 'https://files.menudino.com/cardapios/2305/283.jpg',
        },
        {
            product_id: `${Math.round(Math.random() * 1000)}`,
            name: 'Healthy Hydration Pack',
            price: '30,00',
            category_id: 6,
            ingredients: 'Coconut Water, Green Tea, Lemon Water, Infused Water',
            description: 'Stay hydrated with our healthy pack of drinks, full of antioxidants and vitamins.',
            product_image_url: 'https://files.menudino.com/cardapios/2305/153.jpg',
        },
        {
            product_id: `${Math.round(Math.random() * 1000)}`,
            name: 'Craft Beer Selection',
            price: '55,00',
            category_id: 6,
            ingredients: 'IPA, Stout, Lager, Ale',
            description: 'Try a variety of our best craft beers with this selection pack.',
            product_image_url: 'https://files.menudino.com/cardapios/2305/276.jpg',
        },
        {
            product_id: `${Math.round(Math.random() * 1000)}`,
            name: 'Healthy Hydration Pack',
            price: '30,00',
            category_id: 6,
            ingredients: 'Coconut Water, Green Tea, Lemon Water, Infused Water',
            description: 'Stay hydrated with our healthy pack of drinks, full of antioxidants and vitamins.',
            product_image_url: 'https://files.menudino.com/cardapios/2305/153.jpg',
        },
        {
            product_id: `${Math.round(Math.random() * 1000)}`,
            name: 'Healthy Hydration Pack',
            price: '30,00',
            category_id: 6,
            ingredients: 'Coconut Water, Green Tea, Lemon Water, Infused Water',
            description: 'Stay hydrated with our healthy pack of drinks, full of antioxidants and vitamins.',
            product_image_url: 'https://files.menudino.com/cardapios/2305/153.jpg',
        },
        {
            product_id: `${Math.round(Math.random() * 1000)}`,
            name: 'Healthy Hydration Pack',
            price: '30,00',
            category_id: 7,
            ingredients: 'Coconut Water, Green Tea, Lemon Water, Infused Water',
            description: 'Stay hydrated with our healthy pack of drinks, full of antioxidants and vitamins.',
            product_image_url: 'https://files.menudino.com/cardapios/2305/467.jpg',
        },
        {
            product_id: `${Math.round(Math.random() * 1000)}`,
            name: 'Healthy Hydration Pack',
            price: '30,00',
            category_id: 7,
            ingredients: 'Coconut Water, Green Tea, Lemon Water, Infused Water',
            description: 'Stay hydrated with our healthy pack of drinks, full of antioxidants and vitamins.',
            product_image_url: 'https://files.menudino.com/cardapios/2305/518.jpg',
        },
    ]
})